### PR TITLE
Add KD Boat UI demo

### PR DESCRIPTION
**Pull request by bog-dan-ro**
- Add `Disable framebuffer clears on` Qt5 patch
- Add `Add KD Boat UI Demo`
- Add `qtquickcontrols2-qmlplugins` packagegroups
-

### CODE REVIEW

**Review by bbakram2016 — COMMENTED** [review]
No install rule for this demo?
The binary is then not installed on the filesystem.

**Comment by bog-dan-ro** [comment]
> No install rule for this demo? The binary is then not installed on the filesystem.

The binary is installed properly on the target image, I tested it myself.

**Comment by bbakram2016** [comment]
> > No install rule for this demo? The binary is then not installed on the filesystem.
> 
> The binary is installed properly on the target image, I tested it myself.

Ok good. Changes are approved from my side.

**Comment by BernardPuel** [comment]
hello Bogdan,

After internal review, Qt demo will be integrated in a separate X-Linux package (so outside this layer).
Please contact ST graphics team (Akram) for more details.

**Pull request closed without merging**
